
Force_book = {
    'Affect Mind'	:     '0',
    'Battle Insight'	:     '0',
    'Break'	:     '0',
    'Burst'	:     '0',
    'Defensive Technique'	:     '0',
    'Denounce'	:     '0',
    'Enfeeble'	:     '0',
    'Feedback'	:     '0',
    'Force Disarm'	:     '0',
    'Force Imbuement'	:     '0',
    'Force Leap'	:     '0',
    'Force Push/Pull'	:     '0',
    'Force Shunt'	:     '0',
    'Force Technique'	:     '0',
    'Force Whisper'	:     '0',
    'Give Life'	:     '0',
    'Guidance'	:     '0',
    'Lightning Charge'	:     '0',
    'Mind Trick'	:     '0',
    'Necrotic Charge'	:     '0',
    'Necrotic Touch'	:     '0',
    'Psychic Charge'	:     '0',
    'Pyrokinesis'	:     '0',
    'Rebuke'	:     '0',
    'Resistance'	:     '0',
    'Saber Reflect'	:     '0',
    'Saber Throw'	:     '0',
    'Saber Ward'	:     '0',
    'Seethe'	:     '0',
    'Shock'	:     '0',
    'Slow'	:     '0',
    'Sonic Charge'	:     '0',
    'Sound Trick'	:     '0',
    'Spare the Dying'	:     '0',
    'Spirit Blade'	:     '0',
    'Turbulence'	:     '0',
    'Wall Run'	:     '0',
    'Agile Defense'	:     '1',
    'Armor of Abeloth'	:     '1',
    'Battle Precognition'	:     '1',
    'Beast Trick'	:     '1',
    'Breath Control'	:     '1',
    'Burst of Speed'	:     '1',
    'Cloud Mind'	:     '1',
    'Comprehend Speech'	:     '1',
    'Curse'	:     '1',
    'Dark Side Tendrils'	:     '1',
    'Disperse Force'	:     '1',
    'Dun Moch'	:     '1',
    'Fear'	:     '1',
    'Force Blinding'	:     '1',
    'Force Body'	:     '1',
    'Force Current'	:     '1',
    'Force Focus'	:     '1',
    'Force Intuition'	:     '1',
    'Force Jump'	:     '1',
    'Force Mask'	:     '1',
    'Force Propel'	:     '1',
    'Force Reflect'	:     '1',
    'Heal'	:     '1',
    'Heighten Senses'	:     '1',
    'Heroism'	:     '1',
    'Hex'	:     '1',
    'Improved Feedback'	:     '1',
    'Instinctive Movement'	:     '1',
    'Land Stride'	:     '1',
    'Malacia'	:     '1',
    'Phasestrike'	:     '1',
    'Project'	:     '1',
    'Saber Assault'	:     '1',
    'Sanctuary'	:     '1',
    'Sap Vitality'	:     '1',
    'Sense Emotion'	:     '1',
    'Sense Force'	:     '1',
    'Shadow Sight'	:     '1',
    'Slow Descent'	:     '1',
    'Sustained Lightning'	:     '1',
    'Tapas'	:     '1',
    'Telemetry'	:     '1',
    'Telepathic Link'	:     '1',
    'Tremor'	:     '1',
    'Valor'	:     '1',
    'Wound'	:     '1',
    'Affliction'	:     '2',
    'Animate Weapon'	:     '2',
    'Battle Meditation'	:     '2',
    'Battlemind'	:     '2',
    'Calm Emotions'	:     '2',
    'Coerce Mind'	:     '2',
    'Danger Sense'	:     '2',
    'Dark Shear'	:     '2',
    'Darkness'	:     '2',
    'Drain Vitality'	:     '2',
    'Force Barrier'	:     '2',
    'Force Blind/Deafen'	:     '2',
    'Force Blur'	:     '2',
    'Force Camouflage'	:     '2',
    'Force Concealment'	:     '2',
    'Force Confusion'	:     '2',
    'Force Enlightenment'	:     '2',
    'Force Sight'	:     '2',
    'Force Throw'	:     '2',
    'Force Vision'	:     '2',
    'Hallucination'	:     '2',
    'Improved Pyrokinesis'	:     '2',
    'Improved Saber Throw'	:     '2',
    'Kinetite'	:     '2',
    'Locate Object'	:     '2',
    'Mind Spike'	:     '2',
    'Phasewalk'	:     '2',
    'Probe Mind'	:     '2',
    'Pull Earthward'	:     '2',
    'Rescue'	:     '2',
    'Restoration'	:     '2',
    'Saber Strike'	:     '2',
    'Stun'	:     '2',
    'Stun Droid'	:     '2',
    'Wakefulness'	:     '2',
    'Art of Movement'	:     '3',
    'Aura of Vigor'	:     '3',
    'Beacon of Hope'	:     '3',
    'Bestow Curse'	:     '3',
    'Call Lightning'	:     '3',
    'Choke'	:     '3',
    'Convulsion'	:     '3',
    'Dark Aura'	:     '3',
    'Force Lightning'	:     '3',
    'Force Repulse'	:     '3',
    'Force Scream'	:     '3',
    'Force Suppression'	:     '3',
    'Force Trance'	:     '3',
    'Force Weapon'	:     '3',
    'Horror'	:     '3',
    'Improved Dark Side Tendrils'	:     '3',
    'Knight Speed'	:     '3',
    'Mass Malacia'	:     '3',
    'Morichro'	:     '3',
    'Plague'	:     '3',
    'Plant Surge'	:     '3',
    'Psychometry'	:     '3',
    'Remove Curse'	:     '3',
    'Sever Force'	:     '3',
    'Share Life'	:     '3',
    'Telekinetic Shield'	:     '3',
    'Telekinetic Storm'	:     '3',
    'Aura of Purity'	:     '4',
    'Disable Droid'	:     '4',
    'Dominate Beast'	:     '4',
    'Drain Life'	:     '4',
    'Force Immunity'	:     '4',
    'Freedom of Movement'	:     '4',
    'Grasping Vine'	:     '4',
    'Greater Pyrokinesis'	:     '4',
    'Hysteria'	:     '4',
    'Improved Force Camouflage'	:     '4',
    'Locate Creature'	:     '4',
    'Mind Trap'	:     '4',
    'Saber Onslaught'	:     '4',
    'Shocking Shield'	:     '4',
    'Shroud of Darkness'	:     '4',
    'Control Pain'	:     '5',
    'Dominate Mind'	:     '5',
    'Force Breach'	:     '5',
    'Force Meld'	:     '5',
    'Greater Feedback'	:     '5',
    'Greater Saber Throw'	:     '5',
    'Improved Battle Meditation'	:     '5',
    'Improved Force Barrier'	:     '5',
    'Improved Force Scream'	:     '5',
    'Improved Heal'	:     '5',
    'Improved Phasestrike'	:     '5',
    'Improved Phasewalk'	:     '5',
    'Improved Restoration'	:     '5',
    'Insanity'	:     '5',
    'Mass Animation'	:     '5',
    'Revitalize'	:     '5',
    'Siphon Life'	:     '5',
    'Skill Empowerment'	:     '5',
    'Stasis'	:     '5',
    'Telekinesis'	:     '5',
    'Crush'	:     '6',
    'Eruption'	:     '6',
    'Force Chain Lightning'	:     '6',
    'Greater Heal'	:     '6',
    'Improved Force Immunity'	:     '6',
    'Mass Coerce Mind'	:     '6',
    'Master Malacia'	:     '6',
    'Mind Prison'	:     '6',
    'Rage'	:     '6',
    'Scourge'	:     '6',
    'Telekinetic Burst'	:     '6',
    'True Sight'	:     '6',
    'Wall of Light'	:     '6',
    'Wrack'	:     '6',
    'Destroy Droid'	:     '7',
    'Force Lightning Cone'	:     '7',
    'Force Mend'	:     '7',
    'Force Project'	:     '7',
    'Improved Revitalize'	:     '7',
    'Master Pyrokinesis'	:     '7',
    'Master Saber Throw'	:     '7',
    'Master Speed'	:     '7',
    'Ruin'	:     '7',
    'Whirlwind'	:     '7',
    'Death Field'	:     '8',
    'Dominate Monster'	:     '8',
    'Earthquake'	:     '8',
    'Force Link'	:     '8',
    'Maddening Darkness'	:     '8',
    'Master Force Barrier'	:     '8',
    'Master Force Immunity'	:     '8',
    'Master Force Scream'	:     '8',
    'Mind Blank'	:     '8',
    'Stasis Field'	:     '8',
    'Telekinetic Wave'	:     '8',
    'Force Storm'	:     '9',
    'Kill'	:     '9',
    'Mass Hysteria'	:     '9',
    'Master Battle Meditation'	:     '9',
    'Master Feedback'	:     '9',
    'Master Heal'	:     '9',
    'Master Revitalize'	:     '9',
    'Precognition'	:     '9',
    'Will of the Force'	:     '9'
}

Tech_book = {
    'Acid Splash'	:      '0',
    'Acidic Strike'	:      '0',
    'Assess the Situation'	:      '0',
    'Combustive Shot'	:      '0',
    'Cryogenic Burst'	:      '0',
    'Detonator'	:      '0',
    'Dismantle'	:      '0',
    'Echo Blast' :      '0',
    'Electrical Burst'	:      '0',
    'Electroshock'	:      '0',
    'Encrypted Message'	:      '0',
    'Extinguish'	:      '0',
    'Haywire'	:      '0',
    'Illusory Strike'	:      '0',
    'Ion Blast'	:      '0',
    'Ionic Strike'	:      '0',
    'Itemize'	:      '0',
    'Jet of Flame'	:      '0',
    'Light'	:      '0',
    'Mending'	:      '0',
    'Minor Defibrillation'	:      '0',
    'Minor Hologram'	:      '0',
    'Mobile Lights'	:      '0',
    'On/Off'	:      '0',
    'Pheromone Burst'	:      '0',
    'Poison Spray'	:      '0',
    'Pressure Crush'	:      '0',
    'Reboot'	:      '0',
    'Rime Shot'	:      '0',
    'Rime Strike'	:      '0',
    'Short Circuit'	:      '0',
    'Sonic Shot'	:      '0',
    'Sonic Strike'	:      '0',
    'Spectrum Ray'	:      '0',
    'Stinger'	:      '0',
    'Storming Shot'	:      '0',
    'Targeting Shot'	:      '0',
    'Temporary Boost'	:      '0',
    'Tri-Shot'	:      '0',
    'Venomous Strike'	:      '0',
    'Vortex Shot'	:      '0',
    'Ward'	:      '0',
    'Warding Shot'	:      '0',
    'Warp Strike'	:      '0',
    'Wire Line'	:      '0',
    'Absorb Energy'	:      '1',
    'Acid Wind'	:      '1',
    'Adrenaline'	:      '1',
    'Aid Droid'	:      '1',
    'Alarm'	:      '1',
    'Analyze'	:      '1',
    'Bacta Pack'	:      '1',
    'Barrage'	:      '1',
    'Buffer'	:      '1',
    'Condense/Vaporize'	:      '1',
    'Copy'	:      '1',
    'Countermeasures'	:      '1',
    'Cryogenic Blast'	:      '1',
    'Cryogenic Blow'	:      '1',
    'Cryogenic Wave'	:      '1',
    'Decryption Program'	:      '1',
    'Delayed Detonator'	:      '1',
    'Detect Enhancement'	:      '1',
    'Element of Surprise'	:      '1',
    'Energy Shield'	:      '1',
    'Execute Command'	:      '1',
    'Expeditious Retreat'	:      '1',
    'Flame Sweep'	:      '1',
    'Flash'	:      '1',
    'Gleaming Outline'	:      '1',
    'Hologram'	:      '1',
    'Holographic Disguise'	:      '1',
    'Homing Rockets'	:      '1',
    'Ionic Bond'	:      '1',
    'Jump'	:      '1',
    'Jump Jet'	:      '1',
    'Kolto Pack'	:      '1',
    'Oil Slick'	:      '1',
    'Overload'	:      '1',
    'Poison Dart'	:      '1',
    'Preparedness'	:      '1',
    'Repair Droid'	:      '1',
    'Ring of Fire'	:      '1',
    'Smoke Cloud'	:      '1',
    'Sonic Fists'	:      '1',
    'Spectrum Bolt'	:      '1',
    'Spot the Weakness'	:      '1',
    'Stack the Deck'	:      '1',
    'Tactical Barrier'	:      '1',
    'Target Lock'	:      '1',
    'Time Bomb'	:      '1',
    'Toxin Scan' :      '1',
    'Tracer Bolt'	:      '1',
    'Tracker Droid Interface'	:      '1',
    'Tranquilizer'	:      '1',
    'Translation Program'	:      '1',
    'Voltaic Shielding'	:      '1',
    'Acid Dart'	:      '2',
    'Alter Self' :      '2',
    'Burst of Flame'	:      '2',
    'Capacity Boost'	:      '2',
    'Concealed Caltrops'	:      '2',
    'Cryogenic Volley'	:      '2',
    'Darkvision'	:      '2',
    'Detect Invisibility'	:      '2',
    'Detect Traps'	:      '2',
    'Electromesh'	:      '2',
    'Energetic Burst'	:      '2',
    'Enhance Droid'	:      '2',
    'Frequency Scan'	:      '2',
    'Glide'	:      '2',
    'Greater Energy Shield'	:      '2',
    'Hold Droid'	:      '2',
    'Implant Message'	:      '2',
    'Infiltrate'	:      '2',
    'Irradiate'	:      '2',
    'Jump Pad'	:      '2',
    'Kolto Dispenser'	:      '2',
    'Lesser Mislead'	:      '2',
    'Lock'	:      '2',
    'Magnetic Field'	:      '2',
    'Magnetic Hold'	:      '2',
    'Mirror Image'	:      '2',
    'Motivator Boost'	:      '2',
    'Overheat'	:      '2',
    'Paralyze Humanoid'	:      '2',
    'Pyrotechnics'	:      '2',
    'Release'	:      '2',
    'Shared Shielding'	:      '2',
    'Shatter'	:      '2',
    'Shocking Ray'	:      '2',
    'Smuggle'	:      '2',
    'Spectrum Discharge' :      '2',
    'Toxin Purge'	:      '2',
    'Translocate'	:      '2',
    'Truth Serum'	:      '2',
    'Wire Tow'	:      '2',
    'Autonomous Servant'	:      '3',
    'Bestow Virus'	:      '3',
    'Cryogenic Suspension'	:      '3',
    'Debilitating Gas' :    '3',
    'Destroy Tech'	:      '3',
    'Diminish Tech'	:      '3',
    'Enhance Weapon'	:      '3',
    'Explosion'	:      '3',
    'Fabricate Trap'	:      '3',
    'Flaming Shots'	:      '3',
    'Greater Hologram'	:      '3',
    'Greater Light'	:      '3',
    'Greater Translation Program'	:      '3',
    'Instant Translocation'	:      '3',
    'Invisibility to Cameras'	:      '3',
    'Kolto Cloud'	:      '3',
    'Mutate/Augment'	:      '3',
    'Protection from Energy'	:      '3',
    'Read Memory'	:      '3',
    'Remove Virus'	:      '3',
    'Sabotage Charges'	:      '3',
    'Scramble Interface'	:      '3',
    'Sending'	:      '3',
    'Slow-Release Medpac'	:      '3',
    'Tactical Advantage'	:      '3',
    'Tech Override'	:      '3',
    'Tonal Translocate'	:      '3',
    'Vertical Maneuvering'	:      '3',
    'Ballistic Shield'	:      '4',
    'Cloaking Screen'	:      '4',
    'Corrosive Sphere'	:      '4',
    'Cryogenic Storm'	:      '4',
    'Defibrillate'	:      '4',
    'Elemental Accelerant'	:      '4',
    'Fabricate'	:      '4',
    'Holding Cell'	:      '4',
    'Illusory Terrain'	:      '4',
    'Kolto Reserve'	:      '4',
    'Radiation'	:      '4',
    'Salvo'	:      '4',
    'Scan Area'	:      '4',
    'Sensor Probe'	:      '4',
    'Synchronicity'	:      '4',
    'Wire Bind'	:      '4',
    'Cryogenic Spray'	:      '5',
    'Friendly Fire'	:      '5',
    'Greater Analyze'	:      '5',
    'Greater Translocate'	:      '5',
    'Group Hologram'	:      '5',
    'Immolate'	:      '5',
    'Mass Repair Droid'	:      '5',
    'Mislead'	:      '5',
    'Override Interface'	:      '5',
    'Paralyze Creature'	:      '5',
    'Rewrite Memory'	:      '5',
    'Shutdown'	:      '5',
    'Skill Protocol'	:      '5',
    'Toxic Cloud'	:      '5',
    'Carbon Fog'	:      '6',
    'Carbonite'	:      '6',
    'Contingency'	:      '6',
    'Disintegrate'	:      '6',
    'Disperse Energy'	:      '6',
    'Find the Path'	:      '6',
    'Firestorm'	:      '6',
    'Kolto Infusion'	:      '6',
    'Programmed Illusion'	:      '6',
    'Scrambling Barrier'	:      '6',
    'Security Protocols'	:      '6',
    'Superior Translation Program'	:      '6',
    'Cage'	:      '7',
    'Delayed Explosion'	:      '7',
    'Disassemble'	:      '7',
    'Greater Sabotage Charges'	:      '7',
    'Neurotoxin'	:      '7',
    'Project Hologram'	:      '7',
    'Squad Shield'	:      '7',
    'Tactical Superiority'	:      '7',
    'Antipathy/Sympathy'	:      '8',
    'Energizing Aura'	:      '8',
    'Incendiary Cloud'	:      '8',
    'Scrambling Field'	:      '8',
    'Stun Dart'	:      '8',
    'Carbonite Explosion'	:      '9',
    'Greater Explosion' :       '9',
    'Greater Salvo'	:      '9',
    'Invulnerability'	:      '9',
    'Kolto Waves'	:      '9',
    'Predictive AI'	:      '9'
}